"""
create_biochar_schema

Revision ID: 5c757989da62
Revises: 
Create Date: 2026-07-10 17:12:41.679647
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c757989da62'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID v4 project identifier'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Human-readable project name'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('biochar_batches',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID v4 batch identifier'),
    sa.Column('project_id', sa.String(length=36), nullable=False, comment='FK → projects.id'),
    sa.Column('batch_lot_number', sa.String(length=128), nullable=False, comment='Lot number, unique within its parent project'),
    sa.Column('status', sa.Enum('sourcing_purgatory', 'processing_active', 'lab_certified', 'completed', 'ineligible', name='batch_status_enum', create_constraint=True), nullable=False, comment='Current lifecycle state of the batch'),
    sa.Column('net_sequestration_tco2e', sa.Float(), server_default=sa.text('(0.0)'), nullable=False, comment='Net carbon dioxide removal (tCO₂e)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'batch_lot_number', name='uq_biochar_batches_project_lot')
    )
    with op.batch_alter_table('biochar_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_biochar_batches_batch_lot_number'), ['batch_lot_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_biochar_batches_project_id'), ['project_id'], unique=False)

    op.create_table('distribution_sinks',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID v4 distribution record identifier'),
    sa.Column('batch_id', sa.String(length=36), nullable=False, comment='FK → biochar_batches.id'),
    sa.Column('delivery_ticket_id', sa.String(length=128), nullable=False, comment='Outbound invoice / delivery ticket number (globally unique)'),
    sa.Column('farmer_id', sa.String(length=128), nullable=False, comment='End-user / farmer identifier'),
    sa.Column('shipped_mass_tons', sa.Float(), nullable=False, comment='Mass of biochar shipped (metric tonnes)'),
    sa.Column('sink_latitude', sa.Float(), nullable=True, comment='Delivery-site GPS latitude (browser geotag, nullable)'),
    sa.Column('sink_longitude', sa.Float(), nullable=True, comment='Delivery-site GPS longitude (browser geotag, nullable)'),
    sa.Column('photo_evidence_url', sa.String(length=512), nullable=True, comment='Storage bucket path / URL for delivery photo evidence'),
    sa.Column('attestation_timestamp', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the delivery attestation was recorded'),
    sa.ForeignKeyConstraint(['batch_id'], ['biochar_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('distribution_sinks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_distribution_sinks_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_distribution_sinks_delivery_ticket_id'), ['delivery_ticket_id'], unique=True)

    op.create_table('feedstock_ingests',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID v4 ingest record identifier'),
    sa.Column('batch_id', sa.String(length=36), nullable=False, comment='FK → biochar_batches.id'),
    sa.Column('feedstock_type', sa.Enum('rice_husk', 'wood_residue', 'coffee_hulls', name='feedstock_type_enum', create_constraint=True), nullable=False, comment='Biomass category (rice_husk | wood_residue | coffee_hulls)'),
    sa.Column('source_latitude', sa.Float(), nullable=False, comment='Origin GPS latitude (decimal degrees)'),
    sa.Column('source_longitude', sa.Float(), nullable=False, comment='Origin GPS longitude (decimal degrees)'),
    sa.Column('wet_mass_tons', sa.Float(), nullable=False, comment='Gross wet mass of the feedstock delivery (metric tonnes)'),
    sa.Column('satellite_clearance_status', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='True if satellite land-clearance screening passed'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.ForeignKeyConstraint(['batch_id'], ['biochar_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedstock_ingests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedstock_ingests_batch_id'), ['batch_id'], unique=False)

    op.create_table('lab_assays',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID v4 assay record identifier'),
    sa.Column('batch_id', sa.String(length=36), nullable=False, comment='FK → biochar_batches.id (unique per batch)'),
    sa.Column('organic_carbon_percentage', sa.Float(), nullable=False, comment='Organic carbon fraction (0–100 %)'),
    sa.Column('molar_hc_ratio', sa.Float(), nullable=False, comment='Molar hydrogen-to-carbon ratio (H:C)'),
    sa.Column('verification_tier', sa.Enum('pending', 'standard_200yr', 'high_permanence_1000yr', name='verification_tier_enum', create_constraint=True), nullable=False, comment='Permanence classification tier'),
    sa.Column('certificate_hash', sa.String(length=64), nullable=False, comment='SHA-256 hex digest of the laboratory certificate document'),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when assay results were uploaded (UTC)'),
    sa.ForeignKeyConstraint(['batch_id'], ['biochar_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', name='uq_lab_assays_batch_id')
    )
    with op.batch_alter_table('lab_assays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_assays_batch_id'), ['batch_id'], unique=False)

    op.create_table('pyrolysis_telemetry',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='Auto-increment telemetry row identifier'),
    sa.Column('batch_id', sa.String(length=36), nullable=False, comment='FK → biochar_batches.id'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='Sensor reading wall-clock time (indexed)'),
    sa.Column('kiln_temperature_celsius', sa.Float(), nullable=False, comment='Kiln internal temperature at reading time (°C)'),
    sa.Column('electricity_consumption_kwh', sa.Float(), nullable=False, comment='Cumulative grid electricity draw since last reading (kWh)'),
    sa.Column('fossil_fuel_consumption_liters', sa.Float(), nullable=False, comment='Fossil-fuel consumption since last reading (litres)'),
    sa.ForeignKeyConstraint(['batch_id'], ['biochar_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pyrolysis_telemetry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pyrolysis_telemetry_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index('ix_pyrolysis_telemetry_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pyrolysis_telemetry', schema=None) as batch_op:
        batch_op.drop_index('ix_pyrolysis_telemetry_timestamp')
        batch_op.drop_index(batch_op.f('ix_pyrolysis_telemetry_batch_id'))

    op.drop_table('pyrolysis_telemetry')
    with op.batch_alter_table('lab_assays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_assays_batch_id'))

    op.drop_table('lab_assays')
    with op.batch_alter_table('feedstock_ingests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedstock_ingests_batch_id'))

    op.drop_table('feedstock_ingests')
    with op.batch_alter_table('distribution_sinks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distribution_sinks_delivery_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_distribution_sinks_batch_id'))

    op.drop_table('distribution_sinks')
    with op.batch_alter_table('biochar_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_biochar_batches_project_id'))
        batch_op.drop_index(batch_op.f('ix_biochar_batches_batch_lot_number'))

    op.drop_table('biochar_batches')
    op.drop_table('projects')
    # ### end Alembic commands ###
