"""
create_biochar_schema

Revision ID: 5c757989da62
Revises: 
Create Date: 2026-07-10 17:12:41.679647
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c757989da62'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biochar_batch_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('biochar_batch_id', sa.UUID(), nullable=False),
    sa.Column('pyrolysis_run_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('biochar_inventory',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('electricity_consumption',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('pyrolysis_run_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedstock_suppliers',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedstock_types',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuel_consumption',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('pyrolysis_run_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_movements',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laboratories',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laboratory_approvals',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laboratory_parameters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parameter_name', sa.Text(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('min_limit', sa.Float(), nullable=True),
    sa.Column('max_limit', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parameter_name')
    )
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('gst_number', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('subscription_plan', sa.String(length=50), server_default=sa.text("'Free'"), nullable=False),
    sa.Column('subscription_status', sa.String(length=50), server_default=sa.text("'Active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plant_operators',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('plant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plants',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('plant_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reactor_maintenance',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('reactor_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reactors',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('plant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('storage_locations',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('accepted', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_members',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'Active'"), nullable=True),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('methodology', sa.String(length=255), nullable=True),
    sa.Column('project_type', sa.String(length=50), server_default=sa.text("'Biochar'"), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'Draft'"), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedstock_batches',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('batch_code', sa.String(length=128), nullable=False),
    sa.Column('feedstock_type', sa.String(length=100), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('supplier_contact', sa.String(length=255), nullable=True),
    sa.Column('origin_location', sa.Text(), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('moisture_percent', sa.Float(), nullable=True),
    sa.Column('transport_distance_km', sa.Float(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_code')
    )
    op.create_table('feedstock_deliveries',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['feedstock_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedstock_quality',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['feedstock_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pyrolysis_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('feedstock_batch_id', sa.UUID(), nullable=False),
    sa.Column('run_number', sa.String(length=128), nullable=True),
    sa.Column('reactor_name', sa.String(length=255), nullable=True),
    sa.Column('operator_name', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('average_temperature', sa.Float(), nullable=True),
    sa.Column('maximum_temperature', sa.Float(), nullable=True),
    sa.Column('residence_time_minutes', sa.Integer(), nullable=True),
    sa.Column('electricity_kwh', sa.Float(), nullable=True),
    sa.Column('fuel_used_liters', sa.Float(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['feedstock_batch_id'], ['feedstock_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('biochar_batches',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('pyrolysis_run_id', sa.UUID(), nullable=False),
    sa.Column('batch_code', sa.String(length=128), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('storage_location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'In Storage'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['pyrolysis_run_id'], ['pyrolysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_code')
    )
    op.create_table('reactor_sensor_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('reactor_id', sa.UUID(), nullable=True),
    sa.Column('pyrolysis_run_id', sa.UUID(), nullable=True),
    sa.Column('sensor_name', sa.String(length=100), nullable=True),
    sa.Column('sensor_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['pyrolysis_run_id'], ['pyrolysis_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('biochar_applications',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('biochar_batch_id', sa.UUID(), nullable=True),
    sa.Column('application_site', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('application_rate_kg_ha', sa.Float(), nullable=True),
    sa.Column('area_hectares', sa.Float(), nullable=True),
    sa.Column('application_date', sa.Date(), nullable=True),
    sa.Column('applied_by', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['biochar_batch_id'], ['biochar_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('biochar_samples',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('biochar_batch_id', sa.UUID(), nullable=False),
    sa.Column('sample_code', sa.String(length=128), nullable=False),
    sa.Column('collection_date', sa.Date(), nullable=True),
    sa.Column('sampling_method', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['biochar_batch_id'], ['biochar_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_code')
    )
    op.create_table('shipments',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('biochar_batch_id', sa.UUID(), nullable=True),
    sa.Column('shipment_number', sa.String(length=128), nullable=True),
    sa.Column('destination', sa.Text(), nullable=True),
    sa.Column('transport_company', sa.Text(), nullable=True),
    sa.Column('vehicle_number', sa.Text(), nullable=True),
    sa.Column('shipped_weight_kg', sa.Float(), nullable=True),
    sa.Column('shipped_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['biochar_batch_id'], ['biochar_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_number')
    )
    op.create_table('laboratory_tests',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('sample_id', sa.UUID(), nullable=False),
    sa.Column('laboratory_id', sa.UUID(), nullable=True),
    sa.Column('test_reference', sa.Text(), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('analyst_name', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'Pending'"), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['biochar_samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laboratory_certificates',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('laboratory_test_id', sa.UUID(), nullable=True),
    sa.Column('certificate_number', sa.String(length=128), nullable=True),
    sa.Column('certificate_url', sa.String(length=1024), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['laboratory_test_id'], ['laboratory_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laboratory_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('laboratory_test_id', sa.UUID(), nullable=False),
    sa.Column('parameter_id', sa.UUID(), nullable=False),
    sa.Column('measured_value', sa.Float(), nullable=True),
    sa.Column('pass', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['laboratory_test_id'], ['laboratory_tests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parameter_id'], ['laboratory_parameters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laboratory_results')
    op.drop_table('laboratory_certificates')
    op.drop_table('laboratory_tests')
    op.drop_table('shipments')
    op.drop_table('biochar_samples')
    op.drop_table('biochar_applications')
    op.drop_table('reactor_sensor_logs')
    op.drop_table('biochar_batches')
    op.drop_table('pyrolysis_runs')
    op.drop_table('feedstock_quality')
    op.drop_table('feedstock_deliveries')
    op.drop_table('feedstock_batches')
    op.drop_table('projects')
    op.drop_table('organization_members')
    op.drop_table('invitations')
    op.drop_table('profiles')
    op.drop_table('storage_locations')
    op.drop_table('roles')
    op.drop_table('reactors')
    op.drop_table('reactor_maintenance')
    op.drop_table('plants')
    op.drop_table('plant_operators')
    op.drop_table('organizations')
    op.drop_table('laboratory_parameters')
    op.drop_table('laboratory_approvals')
    op.drop_table('laboratories')
    op.drop_table('inventory_movements')
    op.drop_table('fuel_consumption')
    op.drop_table('feedstock_types')
    op.drop_table('feedstock_suppliers')
    op.drop_table('electricity_consumption')
    op.drop_table('biochar_inventory')
    op.drop_table('biochar_batch_runs')
    # ### end Alembic commands ###
